name: visualarch_v1
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ICONS
  cupertino_icons: ^1.0.6

  #FIREBASE
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.16.0
  firebase_storage: ^11.7.0

  #CORE
  get: ^4.6.6
  layout: ^1.0.5

  #MAPS
  google_maps_flutter: ^2.6.1

  #UTILITIES
  line_awesome_flutter: ^2.0.0
  flutter_svg: ^2.0.10+1
  flutter_otp_text_field: ^1.1.3+2
  wc_form_validators: ^1.0.1
  flutter_native_splash: ^2.4.0
  image_cropper: ^5.0.1
  image_picker: ^1.1.0
  path_provider: ^2.1.3
  flutter_image_compress: ^2.2.0
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.0
  url_launcher: ^6.2.5
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 28 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Thin
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf

    - family: ExtraLight
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf

    - family: SemiBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf