const String logo="assets/images/logo.svg";
const String landingImage="assets/images/landing_image.svg";
const String loginImage="assets/images/login_image.svg";
const String signUpImage="assets/images/sign_up.svg";
const String forgetPasswordImage = "assets/images/forget_password.svg";
const String otpImage= "assets/images/otp_image.svg";
const String miniIcon="assets/images/mini_logo.svg";
const String accIcon="assets/images/account_icon.png";
const String verifyImage="assets/images/verify_image.svg";